site_name: My Project

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - crawtools
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true

nav:
  - API:
      - api.md