site_name: crawtools
site_url: https://crawtools.readthedocs.org

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - crawtools
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true

nav:
  - Home: index.md
  - API:
    - Instruments: api/instruments.md
    - Clock Drift: api/clockdrift.md
    - Compliance: api/compliance
    - FDSN: api/fdsn
    - Mapping: api/mapping
    - Rotation Seismometer: api/rotation_seismometer
    - Webb Data File: api/webb_data_file